<Project>
    <PropertyGroup>
        <!-- Ensure Staging is defined for projects that respect this property -->
        <Configurations>Debug;Staging;Release</Configurations>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>2</WarningLevel>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <DefineConstants>DEBUG;TRACE</DefineConstants>
        <!-- Suppress missing XML comment warning only in Debug -->
        <NoWarn>1591</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Staging' ">
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>3</WarningLevel>
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>
        <Optimize>false</Optimize>
        <DefineConstants>TRACE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <AssemblyKeyContainerName>Icod</AssemblyKeyContainerName>
        <DelaySign>false</DelaySign>
        <DebugType>pdbonly</DebugType>
        <Optimize>true</Optimize>
        <ErrorReport>prompt</ErrorReport>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>
</Project>
