namespace Icod.CoreUtils.Stty;

using System.Collections.ObjectModel;
using System.Globalization;
using Icod.CommandFramework.Terminal;

/// <summary>Describes the result of applying ordered <c>stty</c> settings to a snapshot.</summary>
public sealed class SttyEditResult {
	private readonly ReadOnlyCollection<string> outputLines;

	/// <summary>Initializes an edit result.</summary>
	/// <param name="mode">The resulting complete mode.</param>
	/// <param name="changed">Whether terminal state changed.</param>
	/// <param name="timing">The requested mutation timing.</param>
	/// <param name="outputLines">Report lines generated by settings such as <c>speed</c>.</param>
	public SttyEditResult(
		TerminalModeSnapshot mode,
		bool changed,
		TerminalModeApplyTiming timing,
		IEnumerable<string> outputLines
	) {
		ArgumentNullException.ThrowIfNull( mode );
		ArgumentNullException.ThrowIfNull( outputLines );
		this.Mode = mode;
		this.Changed = changed;
		this.Timing = timing;
		this.outputLines = Array.AsReadOnly( outputLines.ToArray() );
	}

	/// <summary>Gets the resulting complete mode.</summary>
	public TerminalModeSnapshot Mode { get; }

	/// <summary>Gets whether terminal state changed.</summary>
	public bool Changed { get; }

	/// <summary>Gets the requested native application timing.</summary>
	public TerminalModeApplyTiming Timing { get; }

	/// <summary>Gets report lines emitted by settings.</summary>
	public IReadOnlyList<string> OutputLines => this.outputLines;
}

/// <summary>Applies GNU <c>stty</c> setting policy without accessing a terminal endpoint.</summary>
public static class SttyModeEditor {
	private const uint EnableProcessedInput = 0x0001;
	private const uint EnableLineInput = 0x0002;
	private const uint EnableEchoInput = 0x0004;
	private const uint EnableProcessedOutput = 0x0001;
	private const uint EnableWrapAtEolOutput = 0x0002;

	/// <summary>Applies ordered settings to a complete mode snapshot.</summary>
	/// <param name="baseline">The live baseline snapshot.</param>
	/// <param name="settings">The ordered setting operands.</param>
	/// <returns>The edited mode, report output, and mutation timing.</returns>
	/// <exception cref="SttyUsageException">A setting is invalid or unsupported by the snapshot.</exception>
	public static SttyEditResult Apply(
		TerminalModeSnapshot baseline,
		IReadOnlyList<string> settings
	) {
		ArgumentNullException.ThrowIfNull( baseline );
		ArgumentNullException.ThrowIfNull( settings );
		if ( ( 1 == settings.Count ) && LooksSerialized( settings[ 0 ] ) ) {
			if ( !TerminalModeCodec.TryRestore( settings[ 0 ], baseline, out var restored, out var error ) ) {
				throw new SttyUsageException( error ?? "invalid saved terminal state" );
			}
			return new SttyEditResult(
				restored!,
				true,
				DefaultTiming( baseline ),
				Array.Empty<string>()
			);
		}

		var state = new MutableState( baseline );
		var output = new List<string>();
		for ( var index = 0; index < settings.Count; ++index ) {
			var setting = settings[ index ];
			if ( string.IsNullOrWhiteSpace( setting ) ) {
				throw new SttyUsageException( "empty mode setting" );
			}
			if ( setting == "speed" ) {
				if ( TerminalPlatformKind.PosixTermios != state.Mode.Platform ) {
					throw new SttyUsageException( "terminal speed is unsupported for Windows console modes" );
				}
				output.Add( SttyFormatter.FormatSpeed( state.ToSnapshot() ) );
				continue;
			}
			if ( setting is "drain" or "-drain" ) {
				if ( TerminalPlatformKind.PosixTermios != state.Mode.Platform ) {
					throw new SttyUsageException( "drain timing is unsupported for Windows console modes" );
				}
				state.Timing = setting == "drain"
					? TerminalModeApplyTiming.AfterOutputDrained
					: TerminalModeApplyTiming.Immediately;
				continue;
			}
			if ( setting is "ispeed" or "ospeed" ) {
				var value = RequireFollowing( settings, ref index, setting );
				state.SetSpeed( setting == "ispeed", setting == "ospeed", value );
				continue;
			}
			if ( setting == "line" ) {
				var value = RequireFollowing( settings, ref index, setting );
				state.SetLineDiscipline( value );
				continue;
			}
			if ( TryGetControlCharacterIndex( state.Mode, setting, out var controlIndex ) ) {
				var value = RequireFollowing( settings, ref index, setting );
				state.SetControlCharacter( controlIndex, value, setting is "min" or "time" );
				continue;
			}
			if ( ulong.TryParse( setting, NumberStyles.None, CultureInfo.InvariantCulture, out var baud ) ) {
				state.SetSpeed( true, true, baud.ToString( CultureInfo.InvariantCulture ) );
				continue;
			}
			if ( state.ApplyProfileOrFlag( setting ) ) {
				continue;
			}
			throw new SttyUsageException( string.Concat( "invalid argument '", setting, "'" ) );
		}
		return new SttyEditResult(
			state.ToSnapshot(),
			state.Changed,
			state.Timing,
			output
		);
	}

	private static bool LooksSerialized( string value ) {
		return value.Contains( ':' );
	}

	private static TerminalModeApplyTiming DefaultTiming( TerminalModeSnapshot mode ) {
		return TerminalPlatformKind.PosixTermios == mode.Platform
			? TerminalModeApplyTiming.AfterOutputDrained
			: TerminalModeApplyTiming.Immediately;
	}

	private static string RequireFollowing(
		IReadOnlyList<string> settings,
		ref int index,
		string setting
	) {
		if ( ++index >= settings.Count ) {
			throw new SttyUsageException( string.Concat( "missing argument after '", setting, "'" ) );
		}
		return settings[ index ];
	}

	private static bool TryGetControlCharacterIndex(
		TerminalModeSnapshot mode,
		string name,
		out int index
	) {
		index = -1;
		if ( TerminalPlatformKind.PosixTermios != mode.Platform ) {
			return false;
		}
		var mac = 64 == mode.NativeFlagWidth;
		index = name switch {
			"intr" => mac ? 8 : 0,
			"quit" => mac ? 9 : 1,
			"erase" => mac ? 3 : 2,
			"kill" => mac ? 5 : 3,
			"eof" => mac ? 0 : 4,
			"time" => mac ? 17 : 5,
			"min" => mac ? 16 : 6,
			"start" => mac ? 12 : 8,
			"stop" => mac ? 13 : 9,
			"susp" => mac ? 10 : 10,
			"eol" => mac ? 1 : 11,
			"rprnt" => mac ? 6 : 12,
			"discard" => mac ? 15 : 13,
			"werase" => mac ? 4 : 14,
			"lnext" => mac ? 14 : 15,
			"eol2" => mac ? 2 : 16,
			"dsusp" => mac ? 11 : -1,
			"status" => mac ? 18 : -1,
			_ => -1
		};
		return ( 0 <= index ) && ( index < mode.ControlCharacters.Count );
	}

	private sealed class MutableState {
		private readonly byte[] characters;
		private readonly bool mac;
		private ulong inputFlags;
		private ulong outputFlags;
		private ulong controlFlags;
		private ulong localFlags;
		private byte? lineDiscipline;
		private TerminalSpeed inputSpeed;
		private TerminalSpeed outputSpeed;
		private uint consoleMode;

		/// <summary>Initializes mutable command-local state from a complete snapshot.</summary>
		/// <param name="mode">The baseline snapshot.</param>
		public MutableState( TerminalModeSnapshot mode ) {
			this.Mode = mode;
			this.mac = 64 == mode.NativeFlagWidth;
			this.inputFlags = mode.InputFlags;
			this.outputFlags = mode.OutputFlags;
			this.controlFlags = mode.ControlFlags;
			this.localFlags = mode.LocalFlags;
			this.characters = mode.ControlCharacters.ToArray();
			this.lineDiscipline = mode.LineDiscipline;
			this.inputSpeed = mode.InputSpeed ?? default;
			this.outputSpeed = mode.OutputSpeed ?? default;
			this.consoleMode = mode.ConsoleMode ?? 0;
			this.Timing = DefaultTiming( mode );
		}

		/// <summary>Gets the immutable baseline snapshot.</summary>
		public TerminalModeSnapshot Mode { get; }

		/// <summary>Gets whether any state value changed.</summary>
		public bool Changed { get; private set; }

		/// <summary>Gets or sets the requested native application timing.</summary>
		public TerminalModeApplyTiming Timing { get; set; }

		/// <summary>Applies one profile or boolean flag setting.</summary>
		/// <param name="setting">The setting operand.</param>
		/// <returns><see langword="true"/> when the setting was recognized.</returns>
		public bool ApplyProfileOrFlag( string setting ) {
			if ( TerminalPlatformKind.WindowsConsole == this.Mode.Platform ) {
				return this.ApplyWindows( setting );
			}
			return this.ApplyPosix( setting );
		}

		/// <summary>Changes the POSIX line discipline.</summary>
		/// <param name="value">The numeric line discipline.</param>
		public void SetLineDiscipline( string value ) {
			this.RequirePosix( "line discipline" );
			if ( !this.lineDiscipline.HasValue ) {
				throw new SttyUsageException( "line discipline is unsupported by this terminal ABI" );
			}
			if ( !byte.TryParse( value, NumberStyles.None, CultureInfo.InvariantCulture, out var parsed ) ) {
				throw new SttyUsageException( string.Concat( "invalid line discipline '", value, "'" ) );
			}
			this.lineDiscipline = parsed;
			this.Changed = true;
		}

		/// <summary>Changes one POSIX control-character slot.</summary>
		/// <param name="index">The native array index.</param>
		/// <param name="value">The command-line value.</param>
		/// <param name="numericOnly">Whether only a byte-sized decimal value is accepted.</param>
		public void SetControlCharacter( int index, string value, bool numericOnly ) {
			this.RequirePosix( "control characters" );
			this.characters[ index ] = ParseControlCharacter(
				value,
				this.Mode.DisabledControlCharacter,
				numericOnly
			);
			this.Changed = true;
		}

		/// <summary>Changes one or both POSIX speeds.</summary>
		/// <param name="input">Whether to change the input speed.</param>
		/// <param name="output">Whether to change the output speed.</param>
		/// <param name="value">The baud-rate operand.</param>
		public void SetSpeed( bool input, bool output, string value ) {
			this.RequirePosix( "terminal speed" );
			if ( !ulong.TryParse( value, NumberStyles.None, CultureInfo.InvariantCulture, out var baud ) ) {
				throw new SttyUsageException( string.Concat( "invalid speed '", value, "'" ) );
			}
			var native = BaudToNative( baud, this.mac );
			if ( !native.HasValue ) {
				throw new SttyUsageException( string.Concat( "unsupported speed '", value, "'" ) );
			}
			var speed = new TerminalSpeed( native.Value, baud );
			if ( input ) {
				this.inputSpeed = speed;
			}
			if ( output ) {
				this.outputSpeed = speed;
			}
			this.Changed = true;
		}

		/// <summary>Creates the current complete immutable snapshot.</summary>
		/// <returns>The snapshot.</returns>
		public TerminalModeSnapshot ToSnapshot() {
			if ( TerminalPlatformKind.WindowsConsole == this.Mode.Platform ) {
				return TerminalModeSnapshot.CreateWindowsConsole(
					this.Mode.ConsoleDirection!.Value,
					this.consoleMode
				);
			}
			return TerminalModeSnapshot.CreatePosix(
				this.inputFlags,
				this.outputFlags,
				this.controlFlags,
				this.localFlags,
				this.characters,
				this.Mode.DisabledControlCharacter,
				this.Mode.NativeFlagWidth,
				this.lineDiscipline,
				this.inputSpeed,
				this.outputSpeed
			);
		}

		private bool ApplyWindows( string setting ) {
			var enable = !setting.StartsWith( '-' );
			var name = enable ? setting : setting[ 1.. ];
			if ( name is "sane" or "cooked" ) {
				this.RequireWindowsInput( name );
				this.consoleMode |= EnableProcessedInput | EnableLineInput | EnableEchoInput;
				this.Changed = true;
				return true;
			}
			if ( name == "raw" ) {
				this.RequireWindowsInput( name );
				if ( enable ) {
					this.consoleMode &= ~( EnableProcessedInput | EnableLineInput | EnableEchoInput );
				} else {
					this.consoleMode |= EnableProcessedInput | EnableLineInput | EnableEchoInput;
				}
				this.Changed = true;
				return true;
			}
			uint bit;
			if ( TerminalConsoleDirection.Input == this.Mode.ConsoleDirection ) {
				bit = name switch {
					"isig" => EnableProcessedInput,
					"icanon" => EnableLineInput,
					"echo" => EnableEchoInput,
					_ => 0
				};
			} else {
				bit = name switch {
					"opost" => EnableProcessedOutput,
					"onlcr" => EnableWrapAtEolOutput,
					_ => 0
				};
			}
			if ( 0 == bit ) {
				return false;
			}
			if ( enable ) {
				this.consoleMode |= bit;
			} else {
				this.consoleMode &= ~bit;
			}
			this.Changed = true;
			return true;
		}

		private bool ApplyPosix( string setting ) {
			if ( setting is "sane" or "cooked" or "-raw" ) {
				this.ApplySane();
				return true;
			}
			if ( setting == "raw" ) {
				this.ApplyRaw();
				return true;
			}
			if ( setting == "ek" ) {
				this.SetDefaultEraseAndKill();
				return true;
			}
			if ( setting is "nl" or "-nl" ) {
				var nl = setting == "-nl";
				this.SetInput( this.InputMask( "icrnl" ), nl );
				this.SetOutput( this.OutputMask( "onlcr" ), nl );
				return true;
			}
			if ( setting is "evenp" or "parity" or "oddp" or "-evenp" or "-parity" or "-oddp" ) {
				this.ApplyParityAlias( setting );
				return true;
			}
			if ( setting is "pass8" or "-pass8" ) {
				var pass = setting == "pass8";
				this.SetInput( this.InputMask( "istrip" ), !pass );
				this.SetControl( this.ControlMask( "parenb" ), !pass );
				this.SetCharacterSize( pass ? "cs8" : "cs7" );
				return true;
			}
			var enable = !setting.StartsWith( '-' );
			var name = enable ? setting : setting[ 1.. ];
			if ( name is "cs5" or "cs6" or "cs7" or "cs8" ) {
				if ( !enable ) {
					throw new SttyUsageException( string.Concat( "invalid negated character size '-", name, "'" ) );
				}
				this.SetCharacterSize( name );
				return true;
			}
			var mask = this.InputMask( name );
			if ( 0 != mask ) {
				this.SetInput( mask, enable );
				return true;
			}
			mask = this.OutputMask( name );
			if ( 0 != mask ) {
				this.SetOutput( mask, enable );
				return true;
			}
			mask = this.ControlMask( name );
			if ( 0 != mask ) {
				this.SetControl( mask, enable );
				return true;
			}
			mask = this.LocalMask( name );
			if ( 0 != mask ) {
				this.SetLocal( mask, enable );
				return true;
			}
			return false;
		}

		private void ApplySane() {
			foreach ( var name in new[] { "brkint", "icrnl", "ixon", "imaxbel" } ) {
				this.SetInput( this.InputMask( name ), true );
			}
			foreach ( var name in new[] { "ignbrk", "inlcr", "igncr", "ixoff", "istrip", "parmrk" } ) {
				this.SetInput( this.InputMask( name ), false );
			}
			this.SetOutput( this.OutputMask( "opost" ), true );
			this.SetOutput( this.OutputMask( "onlcr" ), true );
			this.SetControl( this.ControlMask( "cread" ), true );
			this.SetControl( this.ControlMask( "parenb" ), false );
			this.SetCharacterSize( "cs8" );
			foreach ( var name in new[] { "isig", "icanon", "iexten", "echo", "echoe", "echok", "echoctl", "echoke" } ) {
				this.SetLocal( this.LocalMask( name ), true );
			}
			foreach ( var name in new[] { "echonl", "noflsh", "tostop", "echoprt", "flusho", "pendin" } ) {
				this.SetLocal( this.LocalMask( name ), false );
			}
			this.SetDefaultEraseAndKill();
		}

		private void ApplyRaw() {
			foreach ( var name in new[] { "brkint", "icrnl", "inpck", "istrip", "ixon", "ixoff" } ) {
				this.SetInput( this.InputMask( name ), false );
			}
			this.SetOutput( this.OutputMask( "opost" ), false );
			this.SetControl( this.ControlMask( "parenb" ), false );
			this.SetCharacterSize( "cs8" );
			foreach ( var name in new[] { "echo", "echonl", "icanon", "isig", "iexten" } ) {
				this.SetLocal( this.LocalMask( name ), false );
			}
			if ( TryGetControlCharacterIndex( this.Mode, "min", out var min ) ) {
				this.characters[ min ] = 1;
			}
			if ( TryGetControlCharacterIndex( this.Mode, "time", out var time ) ) {
				this.characters[ time ] = 0;
			}
			this.Changed = true;
		}

		private void ApplyParityAlias( string setting ) {
			var disable = setting.StartsWith( '-' );
			if ( disable ) {
				this.SetControl( this.ControlMask( "parenb" ), false );
				this.SetCharacterSize( "cs8" );
				return;
			}
			this.SetControl( this.ControlMask( "parenb" ), true );
			this.SetControl( this.ControlMask( "parodd" ), setting == "oddp" );
			this.SetCharacterSize( "cs7" );
		}

		private void SetDefaultEraseAndKill() {
			if ( TryGetControlCharacterIndex( this.Mode, "erase", out var erase ) ) {
				this.characters[ erase ] = 0x7f;
			}
			if ( TryGetControlCharacterIndex( this.Mode, "kill", out var kill ) ) {
				this.characters[ kill ] = 0x15;
			}
			this.Changed = true;
		}

		private void SetCharacterSize( string name ) {
			var sizeMask = this.mac ? 0x300UL : 0x30UL;
			var value = this.mac
				? name switch { "cs5" => 0UL, "cs6" => 0x100UL, "cs7" => 0x200UL, _ => 0x300UL }
				: name switch { "cs5" => 0UL, "cs6" => 0x10UL, "cs7" => 0x20UL, _ => 0x30UL };
			this.controlFlags = ( this.controlFlags & ~sizeMask ) | value;
			this.Changed = true;
		}

		private void SetInput( ulong mask, bool enabled ) {
			if ( 0 == mask ) {
				return;
			}
			this.inputFlags = enabled ? this.inputFlags | mask : this.inputFlags & ~mask;
			this.Changed = true;
		}

		private void SetOutput( ulong mask, bool enabled ) {
			if ( 0 == mask ) {
				return;
			}
			this.outputFlags = enabled ? this.outputFlags | mask : this.outputFlags & ~mask;
			this.Changed = true;
		}

		private void SetControl( ulong mask, bool enabled ) {
			if ( 0 == mask ) {
				return;
			}
			this.controlFlags = enabled ? this.controlFlags | mask : this.controlFlags & ~mask;
			this.Changed = true;
		}

		private void SetLocal( ulong mask, bool enabled ) {
			if ( 0 == mask ) {
				return;
			}
			this.localFlags = enabled ? this.localFlags | mask : this.localFlags & ~mask;
			this.Changed = true;
		}

		private ulong InputMask( string name ) {
			return name switch {
				"ignbrk" => 0x1, "brkint" => 0x2, "ignpar" => 0x4, "parmrk" => 0x8,
				"inpck" => 0x10, "istrip" => 0x20, "inlcr" => 0x40, "igncr" => 0x80,
				"icrnl" => 0x100, "iuclc" => 0x200, "ixon" => 0x400, "ixany" => 0x800,
				"ixoff" => 0x1000, "imaxbel" => 0x2000, "iutf8" => 0x4000,
				_ => 0
			};
		}

		private ulong OutputMask( string name ) {
			return name switch {
				"opost" => 0x1, "olcuc" => 0x2, "onlcr" => 0x4, "ocrnl" => 0x8,
				"onocr" => 0x10, "onlret" => 0x20, "ofill" => 0x40, "ofdel" => 0x80,
				_ => 0
			};
		}

		private ulong ControlMask( string name ) {
			if ( this.mac ) {
				return name switch {
					"cstopb" => 0x400, "cread" => 0x800, "parenb" => 0x1000,
					"parodd" => 0x2000, "hupcl" => 0x4000, "clocal" => 0x8000,
					"crtscts" => 0x30000, _ => 0
				};
			}
			return name switch {
				"cstopb" => 0x40, "cread" => 0x80, "parenb" => 0x100,
				"parodd" => 0x200, "hupcl" => 0x400, "clocal" => 0x800,
				"crtscts" => 0x80000000, _ => 0
			};
		}

		private ulong LocalMask( string name ) {
			if ( this.mac ) {
				return name switch {
					"echoke" => 0x1, "echoe" => 0x2, "echok" => 0x4, "echo" => 0x8,
					"echonl" => 0x10, "echoprt" => 0x20, "echoctl" => 0x40,
					"isig" => 0x80, "icanon" => 0x100, "iexten" => 0x400,
					"tostop" => 0x400000, "flusho" => 0x800000, "pendin" => 0x20000000,
					"noflsh" => 0x80000000, _ => 0
				};
			}
			return name switch {
				"isig" => 0x1, "icanon" => 0x2, "xcase" => 0x4, "echo" => 0x8,
				"echoe" => 0x10, "echok" => 0x20, "echonl" => 0x40, "noflsh" => 0x80,
				"tostop" => 0x100, "echoctl" => 0x200, "echoprt" => 0x400,
				"echoke" => 0x800, "flusho" => 0x1000, "pendin" => 0x4000,
				"iexten" => 0x8000, _ => 0
			};
		}

		private void RequirePosix( string feature ) {
			if ( TerminalPlatformKind.PosixTermios != this.Mode.Platform ) {
				throw new SttyUsageException( string.Concat( feature, " is unsupported for Windows console modes" ) );
			}
		}

		private void RequireWindowsInput( string feature ) {
			if ( TerminalConsoleDirection.Input != this.Mode.ConsoleDirection ) {
				throw new SttyUsageException( string.Concat( "'", feature, "' requires a Windows console input handle" ) );
			}
		}
	}

	private static byte ParseControlCharacter(
		string value,
		byte disabled,
		bool numericOnly
	) {
		if ( value is "undef" or "^-" ) {
			return disabled;
		}
		if ( byte.TryParse( value, NumberStyles.None, CultureInfo.InvariantCulture, out var numeric ) ) {
			return numeric;
		}
		if ( numericOnly ) {
			throw new SttyUsageException( string.Concat( "invalid numeric control value '", value, "'" ) );
		}
		if ( value.StartsWith( "0x", StringComparison.OrdinalIgnoreCase )
			&& byte.TryParse( value[ 2.. ], NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture, out var hexadecimal ) ) {
			return hexadecimal;
		}
		if ( ( 2 == value.Length ) && ( '^' == value[ 0 ] ) ) {
			return '?' == value[ 1 ] ? (byte)0x7f : (byte)( char.ToUpperInvariant( value[ 1 ] ) & 0x1f );
		}
		if ( ( 1 == value.Length ) && ( byte.MaxValue >= value[ 0 ] ) ) {
			return (byte)value[ 0 ];
		}
		throw new SttyUsageException( string.Concat( "invalid control character '", value, "'" ) );
	}

	private static ulong? BaudToNative( ulong baud, bool mac ) {
		if ( mac ) {
			return baud switch {
				0 or 50 or 75 or 110 or 134 or 150 or 200 or 300 or 600 or 1200 or 1800
					or 2400 or 4800 or 9600 or 19200 or 38400 or 57600 or 115200 or 230400 => baud,
				_ => null
			};
		}
		return baud switch {
			0 => 0, 50 => 1, 75 => 2, 110 => 3, 134 => 4, 150 => 5, 200 => 6,
			300 => 7, 600 => 8, 1200 => 9, 1800 => 10, 2400 => 11, 4800 => 12,
			9600 => 13, 19200 => 14, 38400 => 15, 57600 => 4097, 115200 => 4098,
			230400 => 4099, 460800 => 4100, 500000 => 4101, 576000 => 4102,
			921600 => 4103, 1000000 => 4104, 1152000 => 4105, 1500000 => 4106,
			2000000 => 4107, 2500000 => 4108, 3000000 => 4109, 3500000 => 4110,
			4000000 => 4111, _ => null
		};
	}
}
