param(
    [string]$SolutionPath = (Get-ChildItem -Path . -Filter *.sln | Select-Object -First 1).FullName
)

if (-not $SolutionPath) {
    Write-Error "No solution file found in current directory. Run the script from repo root containing the .sln."
    exit 1
}

$tools = @(
    "diff",
    "patch",
    "tar",
    "hostname",
    "ps",
    "kill",
    "df",
    "du",
    "shred"
)

function Write-FileUtf8($path, $content) {
    $dir = Split-Path $path -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    $content | Out-File -Encoding utf8 -FilePath $path -Force
    Write-Output "Wrote: $path"
}

foreach ($tool in $tools) {
    $projDir = $tool
    $assemblyName = "Icod.CoreUtils." + ($tool.Substring(0,1).ToUpper() + $tool.Substring(1))
    $rootNs = $assemblyName
    $csprojPath = Join-Path $projDir ("Icod.CoreUtils." + $tool + ".csproj")

    $csproj = @"
<Project Sdk=""Microsoft.NET.Sdk"">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>$assemblyName</AssemblyName>
    <RootNamespace>$rootNs</RootNamespace>
    <OutputPath>..\bin\`$(Configuration)\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include=""..\Shared\Icod.CoreUtils.Shared.csproj"" />
  </ItemGroup>
</Project>
"@

    # Some utilities don't need Shared but referencing it is harmless and consistent.
    Write-FileUtf8 $csprojPath $csproj

    $program = @"
namespace $rootNs;

using System;

public static class Program
{
    public static int Main(string[] args)
    {
        return Command.Run(args);
    }
}
"@
    Write-FileUtf8 (Join-Path $projDir "Program.cs") $program

    # Tool-specific Command.cs
    switch ($tool) {
        "diff" {
            $body = @'
namespace Icod.CoreUtils.Diff;

using System;
using System.IO;
using System.Linq;
using System.Text;

/// <summary>
/// diff: simple line-oriented comparison producing a minimal unified-like output.
/// Credit: Douglas McIlroy (original diff concepts).
/// Usage: diff <file1> <file2>
/// </summary>
public static class Command
{
    public static int Run(string[] args, TextReader? stdin = null, TextWriter? stdout = null, TextWriter? stderr = null)
    {
        stdout ??= Console.Out;
        stderr ??= Console.Error;

        if (args.Length < 2)
        {
            stderr.WriteLine("Usage: diff <file1> <file2>");
            return 2;
        }

        var aPath = args[0];
        var bPath = args[1];

        string[] aLines;
        string[] bLines;
        try
        {
            aLines = File.ReadAllLines(aPath, Encoding.UTF8);
        }
        catch (Exception ex)
        {
            stderr.WriteLine($"diff: {aPath}: {ex.Message}");
            return 1;
        }

        try
        {
            bLines = File.ReadAllLines(bPath, Encoding.UTF8);
        }
        catch (Exception ex)
        {
            stderr.WriteLine($"diff: {bPath}: {ex.Message}");
            return 1;
        }

        var max = Math.Max(aLines.Length, bLines.Length);
        for (var i = 0; i < max; i++)
        {
            var a = i < aLines.Length ? aLines[i] : null;
            var b = i < bLines.Length ? bLines[i] : null;
            if (a == b) continue;
            if (a is null)
            {
                stdout.WriteLine($"+ {b}");
            }
            else if (b is null)
            {
                stdout.WriteLine($"- {a}");
            }
            else
            {
                stdout.WriteLine($"- {a}");
                stdout.WriteLine($"+ {b}");
            }
        }

        return 0;
    }
}
'@
        }
        "patch" {
            $body = @'
namespace Icod.CoreUtils.Patch;

using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

/// <summary>
/// patch: naive application of simple diff output generated by our `diff` tool.
/// Credit: Larry Wall (patch program origin).
/// Usage: patch <target-file> <patch-file>
/// Notes: supports simple lines prefixed with "-", "+" produced by the companion diff above.
/// Creates a .orig backup before applying.
/// </summary>
public static class Command
{
    public static int Run(string[] args, TextReader? stdin = null, TextWriter? stdout = null, TextWriter? stderr = null)
    {
        stderr ??= Console.Error;
        stdout ??= Console.Out;

        if (args.Length < 2)
        {
            stderr.WriteLine("Usage: patch <target-file> <patch-file>");
            return 2;
        }

        var target = args[0];
        var patchFile = args[1];

        string[] lines;
        try
        {
            lines = File.ReadAllLines(patchFile, Encoding.UTF8);
        }
        catch (Exception ex)
        {
            stderr.WriteLine($"patch: {patchFile}: {ex.Message}");
            return 1;
        }

        List<string> original;
        try
        {
            original = new List<string>(File.ReadAllLines(target, Encoding.UTF8));
        }
        catch (Exception ex)
        {
            stderr.WriteLine($"patch: {target}: {ex.Message}");
            return 1;
        }

        var result = new List<string>();
        var i = 0;
        while (i < lines.Length)
        {
            var line = lines[i];
            if (line.Length == 0)
            {
                i++;
                continue;
            }

            if (line[0] == '+')
            {
                // added line
                result.Add(line.Substring(2));
                i++;
            }
            else if (line[0] == '-')
            {
                // removed line: skip corresponding original line if it matches
                var remove = line.Substring(2);
                if (original.Count > 0)
                {
                    // prefer removing first occurrence
                    original.RemoveAt(0);
                }

                i++;
            }
            else
            {
                // context or fallback: take next original line if any
                if (original.Count > 0)
                {
                    result.Add(original[0]);
                    original.RemoveAt(0);
                }

                i++;
            }
        }

        // append remaining original
        result.AddRange(original);

        try
        {
            File.Copy(target, target + ".orig", overwrite: true);
            File.WriteAllLines(target, result, Encoding.UTF8);
        }
        catch (Exception ex)
        {
            stderr.WriteLine($"patch: apply failed: {ex.Message}");
            return 1;
        }

        stdout.WriteLine($"patch: applied to {target} (backup: {target}.orig)");
        return 0;
    }
}
'@
        }
        "tar" {
            $body = @'
namespace Icod.CoreUtils.Tar;

using System;
using System.IO;
using System.Text;
using System.Linq;
using System.Collections.Generic;
using System.Formats.Tar;

/// <summary>
/// tar: create (-c) or extract (-x) archives. Minimal wrapper around System.Formats.Tar.
/// Credit: Bell Labs (tar origin).
/// Usage:
///   tar -c -f archive.tar file1 file2 ...
///   tar -x -f archive.tar
/// </summary>
public static class Command
{
    public static int Run(string[] args, TextReader? stdin = null, TextWriter? stdout = null, TextWriter? stderr = null)
    {
        stdout ??= Console.Out;
        stderr ??= Console.Error;

        if (args.Length < 3)
        {
            stderr.WriteLine("Usage: tar -c|-x -f <archive> [files...]");
            return 2;
        }

        var mode = args[0];
        var flag = args[1];
        var archive = args[2];

        if (mode == "-c")
        {
            var files = args.Skip(3).ToArray();
            try
            {
                using var fs = File.Open(archive, FileMode.Create, FileAccess.Write);
                using var writer = new TarWriter(fs, leaveOpen: false, entryFormat: TarEntryFormat.Ustar);
                foreach (var file in files)
                {
                    if (!File.Exists(file)) continue;
                    using var fileStream = File.OpenRead(file);
                    var entry = new TarEntry(TarEntryType.RegularFile, Path.GetFileName(file));
                    entry.DataStream = fileStream;
                    writer.WriteEntry(entry);
                }
            }
            catch (Exception ex)
            {
                stderr.WriteLine($"tar: {ex.Message}");
                return 1;
            }

            return 0;
        }
        else if (mode == "-x")
        {
            try
            {
                using var fs = File.OpenRead(archive);
                using var reader = new TarReader(fs, leaveOpen: false);
                TarEntry? entry;
                while ((entry = reader.GetNextEntry()) != null)
                {
                    if (entry.EntryType == TarEntryType.RegularFile)
                    {
                        var outPath = entry.Name;
                        using var outFs = File.Create(outPath);
                        entry.DataStream?.CopyTo(outFs);
                    }
                }
            }
            catch (Exception ex)
            {
                stderr.WriteLine($"tar: {ex.Message}");
                return 1;
            }

            return 0;
        }
        else
        {
            stderr.WriteLine("tar: unknown mode, use -c or -x");
            return 2;
        }
    }
}
'@
        }
        "hostname" {
            $body = @'
namespace Icod.CoreUtils.Hostname;

using System;

/// <summary>
/// hostname: print or set the system host name. Minimal: prints machine name.
/// Credit: Bill Joy and the BSD team.
/// Usage: hostname
/// </summary>
public static class Command
{
    public static int Run(string[] args, System.IO.TextReader? stdin = null, System.IO.TextWriter? stdout = null, System.IO.TextWriter? stderr = null)
    {
        stdout ??= Console.Out;
        stdout.WriteLine(Environment.MachineName);
        return 0;
    }
}
'@
        }
        "ps" {
            $body = @'
namespace Icod.CoreUtils.Ps;

using System;
using System.Diagnostics;
using System.Linq;

/// <summary>
/// ps: list processes (basic). Credit: Bell Labs.
/// Usage: ps
/// </summary>
public static class Command
{
    public static int Run(string[] args, System.IO.TextReader? stdin = null, System.IO.TextWriter? stdout = null, System.IO.TextWriter? stderr = null)
    {
        stdout ??= Console.Out;
        try
        {
            var procs = Process.GetProcesses().OrderBy(p => p.Id);
            stdout.WriteLine($"{"PID",6} {"Name",-30} {"StartTime",-24}");
            foreach (var p in procs)
            {
                string start;
                try
                {
                    start = p.StartTime.ToString("s");
                }
                catch
                {
                    start = "";
                }

                stdout.WriteLine($"{p.Id,6} {p.ProcessName,-30} {start,-24}");
            }

            return 0;
        }
        catch (Exception ex)
        {
            stderr?.WriteLine($"ps: {ex.Message}");
            return 1;
        }
    }
}
'@
        }
        "kill" {
            $body = @'
namespace Icod.CoreUtils.Kill;

using System;
using System.Diagnostics;

/// <summary>
/// kill: send termination to processes by PID (supports -9 to force).
/// Credit: Dennis Ritchie and Ken Thompson.
/// Usage: kill <pid> [pid...], or kill -9 <pid>
/// Note: on Windows, only Process.Kill() is used; on Unix this will send a termination.
/// </summary>
public static class Command
{
    public static int Run(string[] args, System.IO.TextReader? stdin = null, System.IO.TextWriter? stdout = null, System.IO.TextWriter? stderr = null)
    {
        stderr ??= Console.Error;
        if (args.Length == 0)
        {
            stderr.WriteLine("Usage: kill [-9] <pid> [pid...]");
            return 2;
        }

        var force = false;
        var idx = 0;
        if (args[0] == "-9")
        {
            force = true;
            idx = 1;
        }

        var exit = 0;
        for (; idx < args.Length; idx++)
        {
            if (!int.TryParse(args[idx], out var pid))
            {
                stderr.WriteLine($"kill: invalid pid: {args[idx]}");
                exit = 1;
                continue;
            }

            try
            {
                var p = Process.GetProcessById(pid);
                p.Kill(); // best-effort
            }
            catch (Exception ex)
            {
                stderr.WriteLine($"kill: {pid}: {ex.Message}");
                exit = 1;
            }
        }

        return exit;
    }
}
'@
        }
        "df" {
            $body = @'
namespace Icod.CoreUtils.Df;

using System;
using System.IO;
using System.Linq;

/// <summary>
/// df: show disk space usage for mounted drives or a specific path.
/// Credit: Dennis Ritchie and Ken Thompson.
/// Usage: df [path]
/// </summary>
public static class Command
{
    public static int Run(string[] args, System.IO.TextReader? stdin = null, System.IO.TextWriter? stdout = null, System.IO.TextWriter? stderr = null)
    {
        stdout ??= Console.Out;
        var path = args.Length > 0 ? args[0] : null;

        try
        {
            if (path is null)
            {
                var drives = DriveInfo.GetDrives().Where(d => d.IsReady);
                foreach (var d in drives)
                {
                    var total = d.TotalSize;
                    var free = d.TotalFreeSpace;
                    var used = total - free;
                    var pct = total == 0 ? 0 : (int)((used * 100L) / total);
                    stdout.WriteLine($"{d.Name}\t{Bytes(total)}\t{Bytes(free)}\t{pct}%");
                }
            }
            else
            {
                var di = new DriveInfo(Path.GetPathRoot(Path.GetFullPath(path)) ?? path);
                var total = di.TotalSize;
                var free = di.TotalFreeSpace;
                var used = total - free;
                var pct = total == 0 ? 0 : (int)((used * 100L) / total);
                stdout.WriteLine($"{di.Name}\t{Bytes(total)}\t{Bytes(free)}\t{pct}%");
            }

            return 0;
        }
        catch (Exception ex)
        {
            stderr?.WriteLine($"df: {ex.Message}");
            return 1;
        }
    }

    private static string Bytes(long v)
    {
        if (v < 1024) return v + "B";
        if (v < 1024L * 1024) return (v / 1024) + "K";
        if (v < 1024L * 1024 * 1024) return (v / (1024 * 1024)) + "M";
        return (v / (1024L * 1024 * 1024)) + "G";
    }
}
'@
        }
        "du" {
            $body = @'
namespace Icod.CoreUtils.Du;

using System;
using System.IO;
using System.Linq;

/// <summary>
/// du: compute disk usage (recursive). Minimal: prints total bytes for each given path.
/// Credit: Dennis Ritchie.
/// Usage: du [path...]
/// </summary>
public static class Command
{
    public static int Run(string[] args, System.IO.TextReader? stdin = null, System.IO.TextWriter? stdout = null, System.IO.TextWriter? stderr = null)
    {
        stdout ??= Console.Out;
        stderr ??= Console.Error;

        var paths = args.Length > 0 ? args : new string[] { "." };
        var exit = 0;
        foreach (var p in paths)
        {
            try
            {
                var size = GetSize(new DirectoryInfo(p));
                stdout.WriteLine($"{size}\t{p}");
            }
            catch (Exception ex)
            {
                stderr.WriteLine($"du: {p}: {ex.Message}");
                exit = 1;
            }
        }

        return exit;
    }

    private static long GetSize(DirectoryInfo dir)
    {
        long total = 0;
        FileInfo[] files = Array.Empty<FileInfo>();
        DirectoryInfo[] subdirs = Array.Empty<DirectoryInfo>();
        try
        {
            files = dir.GetFiles();
            subdirs = dir.GetDirectories();
        }
        catch
        {
            return 0;
        }

        foreach (var f in files) total += f.Length;
        foreach (var d in subdirs) total += GetSize(d);
        return total;
    }
}
'@
        }
        "shred" {
            $body = @'
namespace Icod.CoreUtils.Shred;

using System;
using System.IO;
using System.Security.Cryptography;
using System.Text;

/// <summary>
/// shred: overwrite a file several times with random data then optionally delete.
/// Credit: Colin Plumb.
/// Usage: shred [-n passes] [-u] file
/// </summary>
public static class Command
{
    public static int Run(string[] args, System.IO.TextReader? stdin = null, System.IO.TextWriter? stdout = null, System.IO.TextWriter? stderr = null)
    {
        stderr ??= Console.Error;
        if (args.Length == 0)
        {
            stderr.WriteLine("Usage: shred [-n passes] [-u] file");
            return 2;
        }

        var passes = 3;
        var remove = false;
        var list = new System.Collections.Generic.List<string>();
        for (var i = 0; i < args.Length; i++)
        {
            if (args[i] == "-u") { remove = true; continue; }
            if (args[i] == "-n" && i + 1 < args.Length)
            {
                if (int.TryParse(args[i+1], out var p)) { passes = p; }
                i++;
                continue;
            }
            list.Add(args[i]);
        }

        var exit = 0;
        foreach (var f in list)
        {
            try
            {
                if (!File.Exists(f)) { stderr.WriteLine($"shred: {f}: No such file"); exit = 1; continue; }
                var fi = new FileInfo(f);
                var length = fi.Length;
                using var rng = RandomNumberGenerator.Create();
                var buffer = new byte[8192];
                for (var pass = 0; pass < passes; pass++)
                {
                    using var fs = new FileStream(f, FileMode.Open, FileAccess.Write);
                    fs.Seek(0, SeekOrigin.Begin);
                    var remaining = length;
                    while (remaining > 0)
                    {
                        rng.GetBytes(buffer);
                        var toWrite = (int)Math.Min(buffer.Length, remaining);
                        fs.Write(buffer, 0, toWrite);
                        remaining -= toWrite;
                    }

                    fs.Flush(true);
                }

                if (remove)
                {
                    File.Delete(f);
                }
            }
            catch (Exception ex)
            {
                stderr.WriteLine($"shred: {f}: {ex.Message}");
                exit = 1;
            }
        }

        return exit;
    }
}
'@
        }
    }

    # write Command.cs
    $srcPath = Join-Path $projDir "src"
    $cmdPath = Join-Path $srcPath "Command.cs"
    Write-FileUtf8 $cmdPath $body

    # add to solution
    dotnet sln $SolutionPath add $csprojPath | Out-Null
    Write-Output "Added project $csprojPath to solution"
}

Write-Output "All tools created and added to solution. Run: dotnet build `"$SolutionPath`" -c Staging"
