namespace Icod.CoreUtils.Patch;

using System;
using System.IO;
using System.Text;
using System.Collections.Generic;

/// <summary>
/// patch: naive application of simple diff output generated by our `diff` tool.
/// Credit: Larry Wall (patch program origin).
/// Ported to .NET by Timothy J. Bruce &lt;uniblab@hotmail.com&gt;
/// Usage: patch &lt;target-file&gt; &lt;patch-file&gt;
/// Notes: supports simple lines prefixed with "-", "+" produced by the companion diff above.
/// Creates a .orig backup before applying.
/// </summary>
public static class Command {
	public static int Run( string[] args, TextReader? stdin = null, TextWriter? stdout = null, TextWriter? stderr = null ) {
		stderr ??= Console.Error;
		stdout ??= Console.Out;

		if ( args.Length < 2 ) {
			stderr.WriteLine( "Usage: patch <target-file> <patch-file>" );
			return 2;
		}

		var target = args[ 0 ];
		var patchFile = args[ 1 ];

		string[] lines;
		try {
			lines = File.ReadAllLines( patchFile, Encoding.UTF8 );
		} catch ( Exception ex ) {
			stderr.WriteLine( $"patch: {patchFile}: {ex.Message}" );
			return 1;
		}

		List<string> original;
		try {
			original = new List<string>( File.ReadAllLines( target, Encoding.UTF8 ) );
		} catch ( Exception ex ) {
			stderr.WriteLine( $"patch: {target}: {ex.Message}" );
			return 1;
		}

		var result = new List<string>();
		var i = 0;
		while ( i < lines.Length ) {
			var line = lines[ i ];
			if ( line.Length == 0 ) {
				i++;
				continue;
			}

			if ( line[ 0 ] == '+' ) {
				// added line
				result.Add( line[ 2.. ] );
				i++;
			} else if ( line[ 0 ] == '-' ) {
				// removed line: skip corresponding original line if it matches
				var remove = line[ 2.. ];
				if ( original.Count > 0 ) {
					// prefer removing first occurrence
					original.RemoveAt( 0 );
				}

				i++;
			} else {
				// context or fallback: take next original line if any
				if ( original.Count > 0 ) {
					result.Add( original[ 0 ] );
					original.RemoveAt( 0 );
				}

				i++;
			}
		}

		// append remaining original
		result.AddRange( original );

		try {
			File.Copy( target, target + ".orig", overwrite: true );
			File.WriteAllLines( target, result, Encoding.UTF8 );
		} catch ( Exception ex ) {
			stderr.WriteLine( $"patch: apply failed: {ex.Message}" );
			return 1;
		}

		stdout.WriteLine( $"patch: applied to {target} (backup: {target}.orig)" );
		return 0;
	}
}
